version: "3.8"

networks:
  prod:

services:
  web_server:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
      - frontend
      - portainer
    networks:
      - prod
    restart: on-failure:5 

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./.env
    networks:
      - prod
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "backend:172.18.0.4"
    restart: on-failure:5 

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - ./.env
    networks:
      - prod
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    restart: on-failure:5 

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    networks:
      - prod
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: on-failure:5 

volumes:
  portainer_data:
